# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Look at this Hunter!
email: youknowmyemail@mail.com
description: > # this means to ignore newlines until "baseurl:"
 I do not want anyone to find this website. Noor just want to show off to Hunter. Happy writing
 homework problem :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Don't have a twitter
github_username:  Who cares

# Build settings
markdown: kramdown
